### ISSUE TITLE
[Question] View and Controllers design

### ISSUE THREAD

**Issue by viniciusccarvalho** [gluonhq/ignite#20]
Hi folks, I hope you don't mind me using this as a question spot, could not really find a place to ask for guidance.

As I design my app (I'm not a javafx person, but I wrote swing/swt and android apps in the past). I have been thinking about some design choices.

First I really enjoy ignite, but I'm having a hard time coming to terms with the FXMLView and Controller overlap in some cases, please allow me to elaborate.

When my view is mostly driven by FXML that FXMLView is really a nice fit, although I find it to be mostly an empty shell class, since all logic is within the controller.

But I started to bump into cases where FXML is not enough, and what I'm usually doing is having a root container on my fxml file, and the controller defining a series of view elements (such as Controls). 

And this is where my problem lies, I can't really declare the controls on the view, because the controller will have no access to them. But it seems that in this case the View is kinda redundant, and I should just have View that acts as a controller too handling all the logic.

Any thoughts on this? I thought this to be an interesting topic for beginners like myself.

Cheers

**Comment by eugener** [comment]
This is exactly where 2 "worlds" collide, sort of. One is the compile-time Micronaut DI, another is a reflection based FXML design.  
The best combination we found so far is to make controllers injectable. Not sure we have a way to go around reflection, i.e loading controller class by name, which goes against principles of Micronaut. 

The `FXMLView` concept is based on reflection too, unfortunately.. since we go by naming convention (check out the implementation in [`FXMLRootProvider`](https://github.com/gluonhq/ignite/blob/master/micronaut/src/main/java/com/gluonhq/ignite/micronaut/FXMLRootProvider.java)). 
I can think of two possible improvements here:
- we allow for the case where view file does exist and search for controller and/or fxml file too.
- it might be possible to design some kind of annotation based system, to mark related classes, but that means more code for developers ultimately. 

The view class is not totally redundant though - it serves 2 purposes:
1. it defines the naming convention/package 
2. it allows to retrieve the root control 

So you don't usually declare controls on the view (unless you want non-FXML, hand coded view, which might even have logic in it), but it  possible to treat a view as UI fragment or micro-frontend, and then assemble a bigger view out of such fragments. In fact, readme shows an example of such pattern (see `ContentView` class)

Hopefully you find the answers here...  let me know if you don't  :)

**Comment by viniciusccarvalho** [comment]
That was very helpful @eugener , and thanks for taking the time to explain it to me.

So I guess I'm in the right direction then. I do welcome the integration in lieu of having the View classes as just a mechanism to bind it all together.

I am following the "fragment" route, but the only change I made is:

My main view is a BorderPane, where toolbar, left drawer and main content are setup (but I'm doing this on the controller)

I decided to use the controller along with @FXML annotations in it (I had to make it Initializable) but then I configure all the controls defined in the fxml, or in some cases I create some programatic.

The huge benefit I saw with integration with micronaut (besides DI) is that I got a EventBus for free :) 

So actions from the DrawerController emit events that the MainController listens to and it then swap views at the Center pane of the BorderPane.

Same approach I'm using for notifications on errors, progress bars on footer and as a general way of communicating across controllers without creating a dependency amongst them.

It's a journey, so far it is working. This is a personal project for the time being, but gathering valuable lessons if the need arises one day.

Thank you very much for the insights

**Comment by eugener** [comment]
Sounds pretty good. 
Even though event bus functionality in Micronaut is pretty simple, JavaFX does have a an event system, which becomes very helpful when you need to work events within complex node hierarchies. it is much more complex comparing to Micronaut but can accomplish a lot more when it comes to advanced UIs
